window.trackerData = {
  priorities: [
    {
      stage: "Step 1",
      content: "Transformer fundamentals + language model basics",
      priority: "Foundation, quick review",
    },
    {
      stage: "Step 2",
      content: "Preference learning math and data: Bradley-Terry, chosen/rejected pairs",
      priority: "Highest",
    },
    {
      stage: "Step 3",
      content: "Run a classic outcome reward model with TRL",
      priority: "Highest, build intuition",
    },
    {
      stage: "Steps 4-5",
      content: "PRM annotation, loss, aggregation, and core paper reading",
      priority: "Main track",
    },
    {
      stage: "Engineering",
      content: "PyTorch + Transformers + TRL",
      priority: "Throughout",
    },
    {
      stage: "Advanced",
      content: "RLHF/PPO, DPO, VLM-based reward models",
      priority: "Can wait",
    },
  ],
  tasks: [
    {
      stage: "Step 1: Transformer and language model basics",
      title: "Understand Transformer fundamentals",
      detail: "Explain self-attention, Q/K/V, multi-head attention, positional encoding, residual connections, layer norm, and FFN blocks.",
      priority: "Foundation",
      progress: 100,
      status: "done",
    },
    {
      stage: "Step 1: Transformer and language model basics",
      title: "Explain the relationship between pretraining and SFT",
      detail: "SFT is instruction tuning on top of a pretrained LM, and it provides a useful base for reward modeling.",
      priority: "Quick review",
      progress: 80,
      status: "active",
    },
    {
      stage: "Step 1: Transformer and language model basics",
      title: "Explain the next-token prediction objective",
      detail: "The base LM predicts the next token as a vocabulary classification problem trained with cross-entropy loss.",
      priority: "Quick review",
      progress: 80,
      status: "active",
    },
    {
      stage: "Step 2: Preference learning core",
      title: "Understand chosen vs rejected preference pairs",
      detail: "Understand how preference pairs are annotated, cleaned, constructed, and why RM training learns relative preference.",
      priority: "Highest",
      progress: 35,
      status: "active",
    },
    {
      stage: "Step 2: Preference learning core",
      title: "Derive the Bradley-Terry pairwise ranking loss",
      detail: "Core formula: loss = -log(sigmoid(r_chosen - r_rejected)). Focus on the preference probability assumption behind the sigmoid reward difference.",
      priority: "Highest",
      progress: 20,
      status: "active",
    },
    {
      stage: "Step 2: Preference learning core",
      title: "Understand reward model architecture changes",
      detail: "Replace the LM head with a scalar reward head, usually using the hidden state of the final valid token.",
      priority: "Highest",
      progress: 10,
      status: "active",
    },
    {
      stage: "Step 3: Classic RM / ORM",
      title: "Use AutoModelForSequenceClassification as the reward head",
      detail: "Set num_labels=1 so the model outputs a scalar reward.",
      priority: "Highest",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 3: Classic RM / ORM",
      title: "Run a full TRL RewardTrainer experiment",
      detail: "Start with a small dataset and run a Bradley-Terry reward model end to end to build training intuition.",
      priority: "Highest",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 3: Classic RM / ORM",
      title: "Verify which token produces the reward score",
      detail: "Understand how padding, attention masks, and the last non-pad token affect reward computation.",
      priority: "Highest",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 4: PRM step annotation",
      title: "Understand the PRM800K human step-labeling setup",
      detail: "Understand how each reasoning step is labeled as correct, incorrect, or neutral.",
      priority: "Main track",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 4: PRM step annotation",
      title: "Understand Monte Carlo rollout labeling",
      detail: "Study the Math-Shepherd labeling idea and how Web-Shepherd borrows related methods.",
      priority: "Main track",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 4: PRM step annotation",
      title: "Choose the step-level label design",
      detail: "Decide whether the PRM target should be categorical labels, such as correct/incorrect/neutral, or regression scores.",
      priority: "Main track",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 4: PRM score aggregation",
      title: "Understand how step scores become trajectory scores",
      detail: "Compare min, product, and last-step aggregation strategies, and understand how they affect downstream search.",
      priority: "Main track",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 5: Core papers",
      title: "Read Web-Shepherd closely",
      detail: "Understand how its PRM is trained and how WebRewardBench is constructed and evaluated.",
      priority: "Main track",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 5: Core papers",
      title: "Read Math-Shepherd closely",
      detail: "Understand how its PRM annotation and training differ from Web-Shepherd.",
      priority: "Main track",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Step 5: Core papers",
      title: "Connect paper methods to prompt-engineering iteration",
      detail: "Clarify how PRMs can be used for evaluation, filtering, search, and prompt improvement.",
      priority: "Main track",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Engineering implementation",
      title: "Master the TRL RewardTrainer training flow",
      detail: "Cover data format, collators, training arguments, evaluation, checkpoints, and logging.",
      priority: "Throughout",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Engineering implementation",
      title: "Handle variable-length sequences, padding, and attention masks",
      detail: "Focus on reward extraction positions and avoid scoring pad tokens or wrong positions after truncation.",
      priority: "Throughout",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Engineering implementation",
      title: "Convert the ORM pipeline into a step-level PRM pipeline",
      detail: "Move from response-level chosen/rejected data to step-level data, losses, and aggregation.",
      priority: "Throughout",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Engineering implementation",
      title: "Integrate with WebRewardBench",
      detail: "Make PRM outputs usable for WebRewardBench-style evaluation.",
      priority: "Throughout",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Advanced",
      title: "RLHF / PPO loop",
      detail: "Understand how reward models drive policy optimization after the PRM flow is working.",
      priority: "Can wait",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Advanced",
      title: "DPO",
      detail: "Understand how DPO removes the explicit reward model and how it relates to the PRM path.",
      priority: "Can wait",
      progress: 0,
      status: "todo",
    },
    {
      stage: "Advanced",
      title: "VLM-based reward models",
      detail: "Add visual modality only after the text-only PRM flow is clear.",
      priority: "Can wait",
      progress: 0,
      status: "todo",
    },
  ],
};
