window.trackerData = {
  priorities: [
    {
      stage: "第一步",
      content: "Transformer 原理 + 语言模型基础",
      priority: "基础，快速确认",
    },
    {
      stage: "第二步",
      content: "偏好学习的数学与数据：Bradley-Terry、chosen/rejected",
      priority: "最高",
    },
    {
      stage: "第三步",
      content: "经典 RM / ORM 用 TRL 跑通",
      priority: "最高，建立手感",
    },
    {
      stage: "第四、五步",
      content: "PRM 标注、loss、聚合策略 + 精读核心论文",
      priority: "主线",
    },
    {
      stage: "工程",
      content: "PyTorch + Transformers + TRL",
      priority: "贯穿全程",
    },
    {
      stage: "进阶",
      content: "RLHF/PPO、DPO、VLM-based RM",
      priority: "可缓",
    },
  ],
  tasks: [
    {
      stage: "第一步：Transformer 与语言模型基础",
      title: "掌握 Transformer 原理",
      detail: "能讲清楚 self-attention、Q/K/V、multi-head attention、position encoding、residual、layer norm、FFN。",
      priority: "基础",
      progress: 100,
      status: "done",
    },
    {
      stage: "第一步：Transformer 与语言模型基础",
      title: "确认预训练 + SFT 的关系",
      detail: "SFT 是在预训练 LM 上做指令微调，为 RM 提供基座。",
      priority: "快速过",
      progress: 80,
      status: "active",
    },
    {
      stage: "第一步：Transformer 与语言模型基础",
      title: "确认 next token prediction 训练目标",
      detail: "本质是对下一个 token 做分类，用交叉熵损失。",
      priority: "快速过",
      progress: 80,
      status: "active",
    },
    {
      stage: "第二步：偏好学习核心",
      title: "理解 chosen vs rejected 偏好对",
      detail: "搞清楚偏好对怎么标注、清洗、构造，以及为什么 RM 学的是相对偏好。",
      priority: "最高",
      progress: 35,
      status: "active",
    },
    {
      stage: "第二步：偏好学习核心",
      title: "推导 Bradley-Terry pairwise ranking loss",
      detail: "核心公式：loss = -log(sigmoid(r_chosen - r_rejected))。重点理解 sigmoid 差值背后的偏好概率假设。",
      priority: "最高",
      progress: 20,
      status: "active",
    },
    {
      stage: "第二步：偏好学习核心",
      title: "理解 RM 架构改造",
      detail: "在 LM 上去掉 LM head，换成输出标量的 reward head，通常取最后一个 token 的 hidden state。",
      priority: "最高",
      progress: 10,
      status: "active",
    },
    {
      stage: "第三步：经典 RM / ORM",
      title: "用 AutoModelForSequenceClassification 做 reward head",
      detail: "num_labels=1，即输出一个标量 reward。",
      priority: "最高",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第三步：经典 RM / ORM",
      title: "用 TRL RewardTrainer 跑通完整训练",
      detail: "先在小数据集上跑通 Bradley-Terry RM，目标是建立训练 loop 手感。",
      priority: "最高",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第三步：经典 RM / ORM",
      title: "确认 reward 分数取哪个 token",
      detail: "理解 padding、attention mask、last non-pad token 如何影响 reward 计算。",
      priority: "最高",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第四步：PRM step 标注",
      title: "理解 PRM800K 人工逐步标注路线",
      detail: "搞清楚每一步 reasoning step 如何被标注为对、错或中性。",
      priority: "主线",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第四步：PRM step 标注",
      title: "理解 Monte Carlo rollout 自动化标注",
      detail: "学习 Math-Shepherd 的标注思路，以及 Web-Shepherd 如何借鉴类似方法。",
      priority: "主线",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第四步：PRM step 标注",
      title: "确定 step-level 标签设计",
      detail: "想清楚 PRM 标签是分类：对/错/中性，还是回归分数。",
      priority: "主线",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第四步：PRM 分数聚合",
      title: "理解 step 分数如何聚合成轨迹分数",
      detail: "比较 min、product、last-step 等策略，以及它们对 search 的影响。",
      priority: "主线",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第五步：核心论文",
      title: "精读 Web-Shepherd",
      detail: "理解它的 PRM 如何训练，WebRewardBench 如何构造和评测。",
      priority: "主线",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第五步：核心论文",
      title: "精读 Math-Shepherd",
      detail: "理解 PRM 标注和训练方式与 Web-Shepherd 的差异。",
      priority: "主线",
      progress: 0,
      status: "todo",
    },
    {
      stage: "第五步：核心论文",
      title: "把论文方法接到 prompt engineering 迭代循环",
      detail: "明确 PRM 如何用于评估、筛选、搜索和改进 prompt。",
      priority: "主线",
      progress: 0,
      status: "todo",
    },
    {
      stage: "工程实现",
      title: "掌握 TRL RewardTrainer 完整训练流程",
      detail: "包括数据格式、collator、训练参数、eval、checkpoint 和日志。",
      priority: "贯穿全程",
      progress: 0,
      status: "todo",
    },
    {
      stage: "工程实现",
      title: "处理变长序列、padding、attention mask 的坑",
      detail: "重点是 reward 取值位置，避免把 pad token 或截断后的错误位置拿去打分。",
      priority: "贯穿全程",
      progress: 0,
      status: "todo",
    },
    {
      stage: "工程实现",
      title: "把 ORM pipeline 改造成 step-level PRM",
      detail: "从 response-level chosen/rejected 改成 step-level 数据、loss 和聚合。",
      priority: "贯穿全程",
      progress: 0,
      status: "todo",
    },
    {
      stage: "工程实现",
      title: "对接 WebRewardBench",
      detail: "让 PRM 输出能用于 WebRewardBench 风格的评测。",
      priority: "贯穿全程",
      progress: 0,
      status: "todo",
    },
    {
      stage: "进阶",
      title: "RLHF / PPO 闭环",
      detail: "理解 RM 如何驱动策略优化，等 PRM 跑通后再深入。",
      priority: "可缓",
      progress: 0,
      status: "todo",
    },
    {
      stage: "进阶",
      title: "DPO",
      detail: "理解如何去掉显式 RM，以及它和 PRM 路线的关系。",
      priority: "可缓",
      progress: 0,
      status: "todo",
    },
    {
      stage: "进阶",
      title: "VLM-based RM",
      detail: "等纯文本 PRM 流程吃透后，再加视觉模态。",
      priority: "可缓",
      progress: 0,
      status: "todo",
    },
  ],
};
